### ISSUE TITLE
读取本地比较大的.txt文件非常卡顿，目前出现于13M的txt文档上

### ISSUE THREAD

**Issue by GitForzhongke** [3529/fish-book#2]

**Comment by 3529** [comment]
版本已经更新，感谢支持，访问 www.fish-book.com  下载最新版本




| |
王先生
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年6月1日 10:24 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | [3529/fish-book] 读取本地比较大的.txt文件非常卡顿，目前出现于13M的txt文档上 (Issue #2) |
