### ISSUE TITLE
功能需求：章节跳转、自动翻页

### ISSUE THREAD

**Issue by dylanblueb** [3529/fish-book#3]
可以跳转书本的进度、章节
可以设置速度自动滚动页面

**Comment by 3529** [comment]
fish-book 小说阅读器版本已经更新，访问下载最新版本，感谢兄弟支持！ www.fish-book.com 






| |
王先生
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年6月6日 10:36 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | [3529/fish-book] 功能需求：章节跳转、自动翻页 (Issue #3) |

可以跳转书本的进度、章节
可以设置速度自动滚动页面
