### ISSUE TITLE
功能需求：阅读器能否根据文本的段落显示，而不是连续显示？

### ISSUE THREAD

**Issue by zhxxkeke** [3529/fish-book#4]
比如文本里有两段内容
    1234
    56789
0987654321

1234 是一段内容
567890987654321 是另外一段内容 

阅读器现在是 1234  56789这样显示 想要实现的是 1234 按下一页在显示567890987654321 这样 如果段落内容超出显示 按下一页继续显示 依次类推，两段内容拼接显示很影响阅读体验 谢谢大佬

还有那个 进度百分比 和 关闭X 也可以隐藏了

**Comment by 3529** [comment]
谢谢建议和支持，后期会尝试解决这个问题。







| |
王先生
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年6月13日 10:35 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | [3529/fish-book] 功能需求：阅读器能否根据文本的段落显示，而不是连续显示？ (Issue #4) |

比如文本里有两段内容
1234
56789
0987654321

1234 是一段内容
567890987654321 是另外一段内容

阅读器现在是 1234 56789这样显示 想要实现的是 1234 按下一页在显示567890987654321 这样 如果段落内容超出显示 按下一页继续显示 依次类推，两段内容拼接显示很影响阅读体验 谢谢大佬
