### ISSUE TITLE
为什么设置上下键或者鼠标上下滚轮的快捷键不生效？

### ISSUE THREAD

**Issue by zhxxkeke** [3529/fish-book#5]
如题，组合快捷键翻页太繁琐了，设置了上下键或者鼠标上下滚轮实现翻页没有生效

**Comment by 3529** [comment]
> 如题，组合快捷键翻页太繁琐了，设置了上下键或者鼠标上下滚轮实现翻页没有生效

官网最新版本已支持滚轮翻页
